name: Publish binaries

on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.version=${{ github.ref }}" -a -o jxv
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.version=${{ github.ref }}"" -a -o jxv.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            jvx
            jvx.exe
